AllCops:
  Exclude:
    - 'extensions/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 120

Metrics/ParameterLists:
  CountKeywordArgs: false

MultilineOperationIndentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma