linters:
  SelectorFormat:
    convention: ^(?:(js)-)?([^[A-B]-]*)(?:-{1,2})?([^[A-B]-]*)$
    ignored_names:
      - how-i-grade
      - noUi-target
      - noUi-base
      - noUi-handle
      - noUi-active
      - noUi-background
      - noUi-origin
      - noUi-stacking
      - noUiSlider
      - noUi-state-drag
