linters:
  SelectorFormat:
    convention: strict_BEM
    ignored_names:
      - noUi-target
      - noUi-base
      - noUi-handle
      - noUi-active
      - noUi-background
      - noUi-origin
      - noUi-stacking
      - noUiSlider
